name: Deploy Web to VPS

on:
  push:
    branches: [ "main" ] # Ou "master", verifique o nome da sua branch principal

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Baixa o código do repositório
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Instala o Flutter no ambiente do GitHub
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      
      # 3. Baixa as dependências e gera o build
      - name: Install dependencies & Build
        run: |
          flutter pub get
          flutter build web --release

      # 4. Envia os arquivos para a VPS via SCP
      - name: Deploy to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          # Copia o conteúdo de build/web para a pasta do servidor
          source: "build/web/*"
          target: "/var/www/smokingbee.com.br"
          # Remove as pastas 'build/web' do caminho no destino, copiando apenas os arquivos internos
          strip_components: 2